---

dist: xenial
language: python
python: 3.8.3
install:
  - pip install -r requirements_dev.txt
  - pip install -e .
script:
  - black --line-length=79 --check .
  - pytest --ignore=setup_project/project_name
  - pytest --ignore=setup_project/project_name --cov=setup_project
    --cov-fail-under=90 --cov-report term-missing
after_success:
  - coveralls
env:
  - PYTHONBREAKPOINT=0
