---

commands: |
    echo Hello
    git status
    git pull origin master
    git checkout -b setup
    git status
    python -m venv environment-name
    echo created environment-name
    echo. >> .gitignore
    echo # Environments >> .gitignore
    echo environment-name/ >> .gitignore
    git pull
    git status
    git add .gitignore; git commit -a -m "Add environment name to .gitignore"
    git push origin setup
    environment-name\\Scripts\\python.exe -m pip --version
    environment-name\\Scripts\\python.exe -m pip install -r requirements_dev.txt
    ren project_name\\project_name.py new_name.py
    ren project_name new_name
    ren tests\\test_project_name.py test_new_name.py
    environment-name\\Scripts\\python.exe -m setup.py sdist bdist_wheel
    environment-name\\Scripts\\python.exe -m pip install -e .
    pytest
    pytest --cov=new_name
    black .
    git add *
    pre-commit install
    pre-commit run --all-files
    git commit -a -m "Create files and run pre-commit"
    git add *
    git commit -a -m "Create files and run pre-commit"
    git status
    git push origin setup
    git status

substitutions:
  - sub: test_project_setup
    loc:
      - repo-name
  - sub: test_project_setup-env
    loc:
      - environment-name
  - sub: new_project
    loc:
      - new_name
